// old script
/*
node {
	stage('Build') {
		echo "Build"
	}
	stage('Test') {
		echo "Test"
	}
}
*/

// Declarative syntax
pipeline {
	agent any
	 environment {
        dockerHome = tool 'Docker-engine'
        mavenHome = tool 'Maven-binaries'
        PATH = "$dockerHome/bin:$mavenHome/bin:$PATH"
    }
    stages {
        stage('Build') {
            steps {
                 dir('currency-exchange-microservice') {
                    sh "mvn clean compile"
                }
            }
        }
        stage('Unit Test'){
            steps{
                  dir('currency-exchange-microservice') {
                    sh "mvn test"
                }
            }
        }
        stage("Integration Test"){
            steps{
                  dir('currency-exchange-microservice') {
                    sh "mvn failsafe:integration-test failsafe:verify"
                }
            }
        }
    }
} 
