// old script
/*
node {
	stage('Build') {
		echo "Build"
	}
	stage('Test') {
		echo "Test"
	}
}
*/

// Declarative syntax
pipeline {
	agent any
	 environment {
        dockerHome = tool 'Docker-engine'
        mavenHome = tool 'Maven-binaries'
        PATH = "$dockerHome/bin:$mavenHome/bin:$PATH"
    }
    stages {
        stage('Build') {
            steps {
                sh "mvn clean compile"
            }
        }
        stage('Unit Test'){
            steps{
                sh "mvn test"
            }
        }
        stage("Integration Test"){
            steps{
                sh "mvn failsafe:integration-test failsafe:verify"
            }
        }
        stage("Docker build"){
            steps{
                script {
                    dockerImage = docker.build("supunganegoda/exchange-microservice:${env.BUILD_TAG}")
                }
            }
        }
    }
} 
