// old script
/*
node {
	stage('Build') {
		echo "Build"
	}
	stage('Test') {
		echo "Test"
	}
}
*/

// Declarative syntax
pipeline {
	agent any
	environment{
		dockerHome = tool 'Docker-engine'
		mavenHome = tool 'Maven-binaries'
		PATH = '$dockerHome/bin:$mavenHome/bin:$PATH'
	}
	stages {
			stage('Build') {
			steps {
				echo "Tool versions"
				sh "mvn --version"
				sh "docker version"
			}
		}

		stage('Test') {
			steps {
				echo "Test"
			}
		}	

		stage('Integration Test') {
			steps {
				echo "Integration Test"
			}
		}	
	}
} 
